import CardAnimals from "@/components/ui/card-animals";

export default function ContentAnimals() {
  return (
    <div className="w-full grid grid-cols-4 gap-3">
      <CardAnimals
        animals={[
          {
            id: "1",
            name: "Scooby Doo",
            race: "Pastor Alemão",
            animal: "dog",
            birth: "29/novembro/2014",
            owner: "Salsicha",
            phone: "(81) 9 9999-9999",
          },
          {
            id: "2",
            name: "Simba",
            race: "Persa",
            animal: "cat",
            birth: "04/novembro/2016",
            owner: "John Doe",
            phone: "(81) 9 9999-9999",
          },
          {
            id: "3",
            name: "Scooby Doo",
            race: "Pastor Alemão",
            animal: "dog",
            birth: "29/novembro/2014",
            owner: "Salsicha",
            phone: "(81) 9 9999-9999",
          },
          {
            id: "4",
            name: "Simba",
            race: "Persa",
            animal: "cat",
            birth: "04/novembro/2016",
            owner: "John Doe",
            phone: "(81) 9 9999-9999",
          },
          {
            id: "1",
            name: "Scooby Doo",
            race: "Pastor Alemão",
            animal: "dog",
            birth: "29/novembro/2014",
            owner: "Salsicha",
            phone: "(81) 9 9999-9999",
          },
          {
            id: "2",
            name: "Simba",
            race: "Persa",
            animal: "cat",
            birth: "04/novembro/2016",
            owner: "John Doe",
            phone: "(81) 9 9999-9999",
          },
          {
            id: "3",
            name: "Scooby Doo",
            race: "Pastor Alemão",
            animal: "dog",
            birth: "29/novembro/2014",
            owner: "Salsicha",
            phone: "(81) 9 9999-9999",
          },
          {
            id: "4",
            name: "Simba",
            race: "Persa",
            animal: "cat",
            birth: "04/novembro/2016",
            owner: "John Doe",
            phone: "(81) 9 9999-9999",
          },
          {
            id: "1",
            name: "Scooby Doo",
            race: "Pastor Alemão",
            animal: "dog",
            birth: "29/novembro/2014",
            owner: "Salsicha",
            phone: "(81) 9 9999-9999",
          },
          {
            id: "2",
            name: "Simba",
            race: "Persa",
            animal: "cat",
            birth: "04/novembro/2016",
            owner: "John Doe",
            phone: "(81) 9 9999-9999",
          },
          {
            id: "3",
            name: "Scooby Doo",
            race: "Pastor Alemão",
            animal: "dog",
            birth: "29/novembro/2014",
            owner: "Salsicha",
            phone: "(81) 9 9999-9999",
          },
          {
            id: "1",
            name: "Scooby Doo",
            race: "Pastor Alemão",
            animal: "dog",
            birth: "29/novembro/2014",
            owner: "Salsicha",
            phone: "(81) 9 9999-9999",
          },
          {
            id: "2",
            name: "Simba",
            race: "Persa",
            animal: "cat",
            birth: "04/novembro/2016",
            owner: "John Doe",
            phone: "(81) 9 9999-9999",
          },
          {
            id: "3",
            name: "Scooby Doo",
            race: "Pastor Alemão",
            animal: "dog",
            birth: "29/novembro/2014",
            owner: "Salsicha",
            phone: "(81) 9 9999-9999",
          },
          {
            id: "4",
            name: "Simba",
            race: "Persa",
            animal: "cat",
            birth: "04/novembro/2016",
            owner: "John Doe",
            phone: "(81) 9 9999-9999",
          },
          {
            id: "4",
            name: "Simba",
            race: "Persa",
            animal: "cat",
            birth: "04/novembro/2016",
            owner: "John Doe",
            phone: "(81) 9 9999-9999",
          },
        ]}
      />
    </div>
  );
}
